# keybinds
unbind C-b
set -g prefix C-a
bind C-a      send-prefix
bind -r ,     previous-window
bind -r .     next-window
bind -r <     swap-window -t :-
bind -r >     swap-window -t :+
bind -r |     split-window -h -c "#{pane_current_path}"
bind -r \\    split-window -h -c "#{pane_current_path}"
bind -r -     split-window -v -c "#{pane_current_path}"
bind -r o     rotate-window
bind -r h     select-pane -L
bind -r j     select-pane -D
bind -r k     select-pane -U
bind -r l     select-pane -R
bind -r H     resize-pane -L 5
bind -r J     resize-pane -D 5
bind -r K     resize-pane -U 5
bind -r L     resize-pane -R 5
bind n        command-prompt 'rename-window %%'
bind N        command-prompt 'rename-session %%'
bind -r x     kill-pane
bind -r X     kill-window
bind r        source-file ~/.config/tmux/tmux.conf \; display-message " * reloaded ~/.config/tmux/tmux.conf"


# behavior
set  -g  base-index 1            # start window numbering from 1 instead of 0
setw -g  pane-base-index 1       # make pane numbering consistent with windows
setw -g  automatic-rename on     # automatically name windows
setw -g  automatic-rename-format '#{b:pane_current_path}'
set  -g  renumber-windows on     # renumber windows when a window is closed
set  -g  set-titles on           # auto set the terminal's window title
# setw -g  mode-mouse on           # copy with mouse in copy mode
# set  -g  mouse-select-pane on    # let mouse switch panes
# set  -g  mouse-resize-pane on
# set  -g  mouse-select-window on
set  -g  display-panes-time 800  # slightly longer pane indicators display time
set  -g  display-time 1000       # slightly longer status messages display time
set  -g  history-limit 5000      # boost history
set  -g  monitor-activity on
set  -g  visual-activity off
set  -s  escape-time 10          # faster command sequences
set  -s  focus-events on
set  -sg repeat-time 600         # increase repeat timeout
setw -g  xterm-keys on


# appearance
set  -g default-terminal "screen-256color"
set  -g status on
set  -g status-interval 2
set  -g status-bg colour233
set  -g status-fg colour244
set  -g status-left-length 20
set  -g status-right-length 150
set  -g status-left "#{?client_prefix,#[fg=colour254]#[bg=colour31]#[bold],#[fg=colour16]#[bg=colour254]#[bold]} #S #{?client_prefix,#[fg=colour31],#[fg=colour254]}#[bg=colour233]#[nobold] "
set  -g status-right "#[fg=colour236,bg=default] #[fg=colour247,bg=colour236] #(date '+%Y-%m-%d')#[fg=colour241,bg=colour236] #[fg=colour252,bg=colour236] #(date '+%H:%M')#[fg=colour252,bg=colour236] #[fg=colour16,bg=colour252,bold]  #(hostname) "
setw -g window-status-format "#[fg=colour244,bg=colour233]#I #[fg=colour240,bg=colour233] #[default]#W "
setw -g window-status-current-format "#[fg=colour233,bg=colour31] #[fg=colour117,bg=colour31]#I  #[fg=colour231,bg=colour31]#W #[fg=colour31,bg=colour233] "
