#!/usr/bin/env bash

# ----- General -----
FULL_NAME="Ryan Hansohn";
EMAIL_ADDRESS="hansohn@users.noreply.github.com";
PHONE_NUMBER="REDACTED";

# ----- Switches
WINDOWS_DEV=true;
iterm_install=false;

# ----- Exports -----
export HOMEBREW_CASK_OPTS="--appdir=/Applications";
