#!/usr/bin/env bash

# ----- General -----
FULL_NAME="";
EMAIL_ADDRESS="";
PHONE_NUMBER="";

# ----- Switches
WINDOWS_DEV=true;
iterm_install=false;

# ----- Exports -----
export HOMEBREW_CASK_OPTS="--appdir=/Applications";
